monolog:
    handlers:
        file_log:
            type: stream
            path: "./var/log/hotel-convert-%kernel.environment%.log"
            level: debug
        console:
            type: console
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
