monolog:
    handlers:
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "./logs/hotel-convert-%kernel.environment%.log"
            level: debug
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
